### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [Bryan-Cee/bryce-robbyrussell#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, I recommend you rename the repo to something less generic than zsh-theme - bryce-robbyrussell would be good.

**Comment by Bryan-Cee** [comment]
@unixorn The screenshot has been updated.
