### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [Bryan-Cee/bryce-robbyrussell#2]
I'm adding this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

Thanks!

**Comment by Bryan-Cee** [comment]
This issue has been resolved by #3. 👍

**Comment by unixorn** [comment]
Awesome, thanks
